tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#fb922a",
        "surface-container-highest": "#dce2f7",
        outline: "#847561",
        "on-tertiary-fixed": "#2f1500",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#534600",
        "on-primary-fixed": "#281800",
        "on-error": "#ffffff",
        "inverse-primary": "#ffba44",
        "primary-container": "#e59e0b",
        "surface-container": "#e9edff",
        "outline-variant": "#d6c4ad",
        "on-surface": "#141b2b",
        "secondary-fixed": "#f9e287",
        "on-error-container": "#93000a",
        surface: "#f9f9ff",
        "secondary-fixed-dim": "#dcc66e",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#614000",
        "secondary-container": "#f6df84",
        "inverse-on-surface": "#edf0ff",
        "tertiary-fixed-dim": "#ffb77d",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#726212",
        "primary-fixed": "#ffddaf",
        "surface-tint": "#805600",
        primary: "#805600",
        "surface-container-low": "#f1f3ff",
        "surface-bright": "#f9f9ff",
        "on-surface-variant": "#514534",
        error: "#ba1a1a",
        "surface-container-high": "#e1e8fd",
        tertiary: "#904d00",
        "surface-variant": "#dce2f7",
        "tertiary-fixed": "#ffdcc3",
        "on-background": "#141b2b",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ffba44",
        "surface-dim": "#d3daef",
        "on-tertiary-fixed-variant": "#6e3900",
        secondary: "#6e5e0d",
        "inverse-surface": "#293040",
        background: "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#643300",
        "on-secondary-fixed": "#221b00",
        "on-primary-container": "#583a00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "space-xl": "2rem",
        margin: "1rem",
        "space-sm": "0.5rem",
        gutter: "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.25rem",
        "space-md": "0.75rem",
        "margin-desktop": "2.5rem",
      },
      fontFamily: {
        "body-sm": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "500" }],
        "headline-xl-mobile": [
          "26px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "800" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "18px",
          { lineHeight: "26px", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "label-lg": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.03em", fontWeight: "700" },
        ],
        "headline-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "800" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" },
        ],
      },
    },
  },
};
